# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
#org.gradle.debug=false
mappingsVersion = 2024.07.07-1.21
modMixinVersion = 0.8.5
mappingsChannel = parchment
modGroup = net.rpgz

## Publishing Porperties
_curseforge_id = 404828
_modrinth_id   = x
## Environment Properties
_minecraft_version     = 1.20.6
_minecraft_version_min = 1.20
_minecraft_version_max = 1.21
_loader                = Forge
_loader_file           = META-INF/mods.toml
_loader_version        = 50.1.0
_loader_version_min    = 50
_loader_version_max    = 52
_unionlib_version      = 12.0.7
_unionlib_version_min  = 12.0.3
_unionlib_version_max  = 12.1.0
## Mod Properties
_mod_name          = rpgz
_mod_id            = rpgz
_mod_version       = 0.7.0
_mod_release       = release
_mod_environment   = client & server
_mod_license       = All Rights Reserved
_mod_authors       = Globox_Z, Stereowalker
_mod_issue_tracker = https://github.com/Globox1997/RpgZ/issues
_mod_page          = https://www.curseforge.com/minecraft/mc-mods/rpgz
_mod_description   = A mod that changes the fishing system to force you to pull real living fish from minecrafts waters. CF https://www.curseforge.com/minecraft/mc-mods/actually-fishing, Modrinth https://modrinth.com/mod/actual-fishing
##Misc Properties
